"""migration

Revision ID: 2ad58b1abc0f
Revises: a23a80ad45a4
Create Date: 2026-05-08 21:38:38.110135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ad58b1abc0f'
down_revision: Union[str, Sequence[str], None] = 'a23a80ad45a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balances',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'history', ['video_id', 'user_id'])
    op.create_unique_constraint(None, 'likes', ['video_id', 'user_id'])
    op.add_column('users', sa.Column('avatar_key', sa.String(length=256), nullable=True))
    op.create_unique_constraint(None, 'users', ['avatar_key'])
    op.add_column('videos', sa.Column('preview_key', sa.String(length=256), nullable=True))
    op.create_unique_constraint(None, 'videos', ['preview_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'videos', type_='unique')
    op.drop_column('videos', 'preview_key')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'avatar_key')
    op.drop_constraint(None, 'likes', type_='unique')
    op.drop_constraint(None, 'history', type_='unique')
    op.drop_table('balances')
    # ### end Alembic commands ###
