"""subscriptions

Revision ID: 57b607c4382c
Revises: 256e0c8ce56f
Create Date: 2026-04-26 15:46:07.739547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57b607c4382c'
down_revision: Union[str, Sequence[str], None] = '256e0c8ce56f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_author_subscriptions_author_id'), 'author_subscriptions', ['author_id'], unique=True)
    op.create_table('user_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('author_subscription_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_subscription_id'], ['author_subscriptions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_subscriptions_author_subscription_id'), 'user_subscriptions', ['author_subscription_id'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_user_id'), 'user_subscriptions', ['user_id'], unique=False)
    op.alter_column('videos', 'visibility',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('PUBLIC', 'PRIVATE', 'SUBSCRIPTION', name='visibility', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'visibility',
               existing_type=sa.Enum('PUBLIC', 'PRIVATE', 'SUBSCRIPTION', name='visibility', native_enum=False),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
    op.drop_index(op.f('ix_user_subscriptions_user_id'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_author_subscription_id'), table_name='user_subscriptions')
    op.drop_table('user_subscriptions')
    op.drop_index(op.f('ix_author_subscriptions_author_id'), table_name='author_subscriptions')
    op.drop_table('author_subscriptions')
    # ### end Alembic commands ###
