"""created all tables

Revision ID: 840b4a25af62
Revises: 0f6eef61d5f8
Create Date: 2026-02-17 22:23:37.035650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '840b4a25af62'
down_revision: Union[str, Sequence[str], None] = '0f6eef61d5f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_refresh',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blacklist_refresh_jti'), 'blacklist_refresh', ['jti'], unique=False)
    op.create_table('history',
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('watched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('video_id', 'user_id')
    )
    op.create_table('likes',
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('video_id', 'user_id')
    )
    op.create_table('video_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=128), nullable=False),
    sa.Column('quality', sa.String(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('bitrate', sa.Integer(), nullable=False),
    sa.Column('codec', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_urls_video_id'), 'video_urls', ['video_id'], unique=False)
    op.drop_index(op.f('ix_history_likes_user_id'), table_name='history_likes')
    op.drop_index(op.f('ix_history_likes_video_id'), table_name='history_likes')
    op.drop_table('history_likes')
    op.add_column('users', sa.Column('role', sa.Enum('USER', 'ADMIN', name='roles', native_enum=False), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.add_column('video_stats', sa.Column('likes', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_video_stats_video_id'), table_name='video_stats')
    op.drop_constraint(op.f('video_stats_video_id_fkey'), 'video_stats', type_='foreignkey')
    op.create_foreign_key(None, 'video_stats', 'videos', ['video_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('video_stats', 'like')
    op.drop_column('video_stats', 'id')
    op.add_column('videos', sa.Column('description', sa.String(length=512), nullable=False))
    op.add_column('videos', sa.Column('processing_status', sa.Enum('UPLOADED', 'PROCESSING', 'READY', 'FAILED', name='processingstatuses', native_enum=False), nullable=False))
    op.add_column('videos', sa.Column('visibility', sa.Enum('PUBLIC', 'PRIVATE', 'UNLISTED', name='visibility', native_enum=False), nullable=False))
    op.add_column('videos', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('videos', 'title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.create_index(op.f('ix_videos_visibility'), 'videos', ['visibility'], unique=False)
    op.drop_constraint(op.f('videos_user_id_fkey'), 'videos', type_='foreignkey')
    op.create_foreign_key(None, 'videos', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('videos', 'path')
    op.drop_column('videos', 'is_open')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('is_open', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('videos', sa.Column('path', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'videos', type_='foreignkey')
    op.create_foreign_key(op.f('videos_user_id_fkey'), 'videos', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_videos_visibility'), table_name='videos')
    op.alter_column('videos', 'title',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('videos', 'created_at')
    op.drop_column('videos', 'visibility')
    op.drop_column('videos', 'processing_status')
    op.drop_column('videos', 'description')
    op.add_column('video_stats', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('video_stats', sa.Column('like', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'video_stats', type_='foreignkey')
    op.create_foreign_key(op.f('video_stats_video_id_fkey'), 'video_stats', 'videos', ['video_id'], ['id'])
    op.create_index(op.f('ix_video_stats_video_id'), 'video_stats', ['video_id'], unique=False)
    op.drop_column('video_stats', 'likes')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'role')
    op.create_table('history_likes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('video_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('history_likes_user_id_fkey')),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name=op.f('history_likes_video_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('history_likes_pkey'))
    )
    op.create_index(op.f('ix_history_likes_video_id'), 'history_likes', ['video_id'], unique=False)
    op.create_index(op.f('ix_history_likes_user_id'), 'history_likes', ['user_id'], unique=False)
    op.drop_index(op.f('ix_video_urls_video_id'), table_name='video_urls')
    op.drop_table('video_urls')
    op.drop_table('likes')
    op.drop_table('history')
    op.drop_index(op.f('ix_blacklist_refresh_jti'), table_name='blacklist_refresh')
    op.drop_table('blacklist_refresh')
    # ### end Alembic commands ###
