"""add payment

Revision ID: a23a80ad45a4
Revises: 57b607c4382c
Create Date: 2026-05-02 18:47:16.426264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a23a80ad45a4'
down_revision: Union[str, Sequence[str], None] = '57b607c4382c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('author_subscription_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'FAILED', name='paymentstatuses', native_enum=False), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('provider_payment_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_subscription_id'], ['author_subscriptions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('author_subscriptions', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.drop_index(op.f('ix_author_subscriptions_author_id'), table_name='author_subscriptions')
    op.create_index(op.f('ix_author_subscriptions_author_id'), 'author_subscriptions', ['author_id'], unique=False)
    op.create_unique_constraint(None, 'user_subscriptions', ['user_id', 'author_subscription_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_subscriptions', type_='unique')
    op.drop_index(op.f('ix_author_subscriptions_author_id'), table_name='author_subscriptions')
    op.create_index(op.f('ix_author_subscriptions_author_id'), 'author_subscriptions', ['author_id'], unique=True)
    op.alter_column('author_subscriptions', 'price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_table('payments')
    # ### end Alembic commands ###
